# Describes the format for available services for telenet_telemeter

switch_wifi:
  description: >
   Enable or disable the wifi.
  fields:
    enable:
      description: >
        Yes to enable wifi, No to disable wifi
      example: "Yes"
      
switch_wifree:
  description: >
    Enable or disable the wifree (open shared wifi network that can be used by other Telenet users too).
  fields:
    enable:
      description: >
        Yes to enable wifree, No to disable wifree
      example: "Yes"